spring.application.name=find_campus

server.port=8085

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/testdb
spring.datasource.username=green
spring.datasource.password=1234

# mybatis
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml
mybatis.type-aliases-package=com.example.find_campus.dto
mybatis.configuration.map-underscore-to-camel-case=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=C:/img/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB