CREATE TABLE AI_ITEM_EMBEDDINGS (
    EMBEDDING_ID NUMBER PRIMARY KEY,
    ITEM_TYPE VARCHAR2(20) NOT NULL,
    ITEM_ID NUMBER NOT NULL,
    MODEL_NAME VARCHAR2(200),
    IMAGE_EMBEDDING CLOB,
    TEXT_EMBEDDING CLOB NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_AI_ITEM_EMBEDDING UNIQUE (ITEM_TYPE, ITEM_ID)
);

CREATE SEQUENCE SEQ_AI_ITEM_EMBEDDINGS START WITH 1 INCREMENT BY 1;

CREATE TABLE AI_RECOMMENDATIONS (
    RECOMMENDATION_ID NUMBER PRIMARY KEY,
    SOURCE_TYPE VARCHAR2(20) NOT NULL,
    SOURCE_ID NUMBER NOT NULL,
    TARGET_TYPE VARCHAR2(20) NOT NULL,
    TARGET_ID NUMBER NOT NULL,
    TOTAL_SCORE NUMBER(8, 5) NOT NULL,
    IMAGE_SCORE NUMBER(8, 5),
    TEXT_SCORE NUMBER(8, 5),
    METADATA_SCORE NUMBER(8, 5),
    REASON CLOB,
    MODEL_NAME VARCHAR2(200),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_AI_RECOMMENDATIONS START WITH 1 INCREMENT BY 1;

CREATE INDEX IX_AI_RECOMMENDATIONS_SRC
    ON AI_RECOMMENDATIONS (SOURCE_TYPE, SOURCE_ID, TOTAL_SCORE DESC);

CREATE INDEX IX_AI_RECOMMENDATIONS_TARGET
    ON AI_RECOMMENDATIONS (TARGET_TYPE, TARGET_ID);
