-- FindCampus AI recommendation tables.
-- Run in Oracle SQL Developer using the same account as Spring.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'AI_ITEM_EMBEDDINGS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE AI_ITEM_EMBEDDINGS (
                EMBEDDING_ID NUMBER PRIMARY KEY,
                ITEM_TYPE VARCHAR2(20) NOT NULL,
                ITEM_ID NUMBER NOT NULL,
                MODEL_NAME VARCHAR2(200),
                IMAGE_EMBEDDING CLOB,
                TEXT_EMBEDDING CLOB,
                CREATED_AT DATE DEFAULT SYSDATE,
                UPDATED_AT DATE DEFAULT SYSDATE,
                CONSTRAINT UK_AI_ITEM_EMBEDDINGS UNIQUE (ITEM_TYPE, ITEM_ID)
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_AI_ITEM_EMBEDDINGS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_AI_ITEM_EMBEDDINGS START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'AI_RECOMMENDATIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE AI_RECOMMENDATIONS (
                RECOMMENDATION_ID NUMBER PRIMARY KEY,
                SOURCE_TYPE VARCHAR2(20) NOT NULL,
                SOURCE_ID NUMBER NOT NULL,
                TARGET_TYPE VARCHAR2(20) NOT NULL,
                TARGET_ID NUMBER NOT NULL,
                TOTAL_SCORE NUMBER(8, 6),
                IMAGE_SCORE NUMBER(8, 6),
                TEXT_SCORE NUMBER(8, 6),
                METADATA_SCORE NUMBER(8, 6),
                REASON CLOB,
                MODEL_NAME VARCHAR2(200),
                CREATED_AT DATE DEFAULT SYSDATE
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_AI_RECOMMENDATIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_AI_RECOMMENDATIONS START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_AI_REC_SOURCE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_AI_REC_SOURCE ON AI_RECOMMENDATIONS (SOURCE_TYPE, SOURCE_ID)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_AI_REC_TARGET';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_AI_REC_TARGET ON AI_RECOMMENDATIONS (TARGET_TYPE, TARGET_ID)';
    END IF;
END;
/

COMMIT;