-- FindCampus chat table setup.
-- 이미 만들어진 객체가 있으면 ORA-00955가 날 수 있습니다. 그 경우에는 다음 CREATE만 건너뛰면 됩니다.

CREATE TABLE CHAT_ROOMS (
    ROOM_ID NUMBER PRIMARY KEY,
    ITEM_TYPE VARCHAR2(20) NOT NULL,
    ITEM_ID NUMBER NOT NULL,
    OWNER_ID NUMBER NOT NULL,
    REQUESTER_ID NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UQ_CHAT_ROOMS UNIQUE (ITEM_TYPE, ITEM_ID, OWNER_ID, REQUESTER_ID)
);

CREATE TABLE CHAT_ROOM_USERS (
    ROOM_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    MUTE_YN CHAR(1) DEFAULT 'N' NOT NULL,
    BLOCKED_YN CHAR(1) DEFAULT 'N' NOT NULL,
    LEFT_YN CHAR(1) DEFAULT 'N' NOT NULL,
    LAST_READ_AT DATE,
    CONSTRAINT PK_CHAT_ROOM_USERS PRIMARY KEY (ROOM_ID, USER_ID)
);

CREATE TABLE CHAT_MESSAGES (
    MESSAGE_ID NUMBER PRIMARY KEY,
    ROOM_ID NUMBER NOT NULL,
    SENDER_ID NUMBER NOT NULL,
    MESSAGE_CONTENT VARCHAR2(1000) NOT NULL,
    READ_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_CHAT_ROOMS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CHAT_MESSAGES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMIT;
