SET DEFINE OFF;

MERGE INTO STORAGE_PLACES S
USING (
    SELECT '학생복지관 2층 학생·장학봉사팀' AS STORAGE_NAME,
           (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE USE_YN = 'Y' AND (LOCATION_NAME = '8. 학생복지관' OR REGEXP_REPLACE(LOCATION_NAME, '^[0-9]+\.\s*', '') = '학생복지관')) AS LOCATION_ID,
           '학생·장학봉사팀' AS MANAGER_NAME,
           '051-629-0514' AS PHONE,
           '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
           '학생복지관 2층 학생·장학봉사팀에서 본인 확인 후 수령합니다.' AS DESCRIPTION
      FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN UPDATE SET
    S.LOCATION_ID = SRC.LOCATION_ID,
    S.MANAGER_NAME = SRC.MANAGER_NAME,
    S.PHONE = SRC.PHONE,
    S.OPERATING_HOURS = SRC.OPERATING_HOURS,
    S.DESCRIPTION = SRC.DESCRIPTION,
    S.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT '중앙도서관 안내데스크(1층 데스크)' AS STORAGE_NAME,
           (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE USE_YN = 'Y' AND (LOCATION_NAME = '10. 중앙도서관' OR REGEXP_REPLACE(LOCATION_NAME, '^[0-9]+\.\s*', '') = '중앙도서관')) AS LOCATION_ID,
           '중앙도서관 1층 데스크' AS MANAGER_NAME,
           '051-629-3118' AS PHONE,
           '평일 09:00 ~ 21:00' AS OPERATING_HOURS,
           '중앙도서관 1층 데스크에서 보관 여부를 확인해 주세요.' AS DESCRIPTION
      FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN UPDATE SET
    S.LOCATION_ID = SRC.LOCATION_ID,
    S.MANAGER_NAME = SRC.MANAGER_NAME,
    S.PHONE = SRC.PHONE,
    S.OPERATING_HOURS = SRC.OPERATING_HOURS,
    S.DESCRIPTION = SRC.DESCRIPTION,
    S.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT '대학본관 1층' AS STORAGE_NAME,
           (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE USE_YN = 'Y' AND (LOCATION_NAME = '1. 대학본관' OR REGEXP_REPLACE(LOCATION_NAME, '^[0-9]+\.\s*', '') = '대학본관')) AS LOCATION_ID,
           '대학본관 안내' AS MANAGER_NAME,
           '051-629-1000' AS PHONE,
           '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
           '대학본관 1층에서 안내에 따라 수령 절차를 진행합니다.' AS DESCRIPTION
      FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN UPDATE SET
    S.LOCATION_ID = SRC.LOCATION_ID,
    S.MANAGER_NAME = SRC.MANAGER_NAME,
    S.PHONE = SRC.PHONE,
    S.OPERATING_HOURS = SRC.OPERATING_HOURS,
    S.DESCRIPTION = SRC.DESCRIPTION,
    S.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

UPDATE FOUND_ITEMS F
   SET STORAGE_ID = (
       SELECT MIN(STORAGE_ID)
         FROM STORAGE_PLACES
        WHERE STORAGE_NAME = '학생복지관 2층 학생·장학봉사팀'
   )
 WHERE F.STORAGE_ID IN (
       SELECT STORAGE_ID
         FROM STORAGE_PLACES
        WHERE STORAGE_NAME IN ('학생장학봉사팀 분실물 센터', '학생장학봉사팀', '학생복지관 보관소')
           OR STORAGE_NAME LIKE '%학생장학봉사팀%'
 );

UPDATE STORAGE_PLACES
   SET USE_YN = 'D'
 WHERE (STORAGE_NAME IN ('학생장학봉사팀 분실물 센터', '학생장학봉사팀', '학생복지관 보관소')
        OR STORAGE_NAME LIKE '%학생장학봉사팀%')
   AND STORAGE_NAME <> '학생복지관 2층 학생·장학봉사팀';

COMMIT;
