DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'INQUIRIES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE INQUIRIES (
            INQUIRY_ID NUMBER PRIMARY KEY,
            USER_ID NUMBER NULL,
            INQUIRY_TYPE VARCHAR2(30) NOT NULL,
            TITLE VARCHAR2(200) NOT NULL,
            CONTENT CLOB NOT NULL,
            REPLY_EMAIL VARCHAR2(200),
            STATUS VARCHAR2(30) DEFAULT ''WAITING'' NOT NULL,
            ANSWER_CONTENT CLOB,
            ANSWERED_AT DATE,
            ANSWER_ADMIN_ID NUMBER,
            CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
            UPDATED_AT DATE
        )';
    END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'ANSWER_CONTENT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (ANSWER_CONTENT CLOB)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'ANSWERED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (ANSWERED_AT DATE)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'ANSWER_ADMIN_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (ANSWER_ADMIN_ID NUMBER)'; END IF;
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_INQUIRIES';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_INQUIRIES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; END IF;
END;
/
COMMIT;