DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'INQUIRIES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE INQUIRIES (
            INQUIRY_ID NUMBER PRIMARY KEY,
            USER_ID NUMBER NULL,
            INQUIRY_TYPE VARCHAR2(30) NOT NULL,
            TITLE VARCHAR2(200) NOT NULL,
            CONTENT CLOB NOT NULL,
            REPLY_EMAIL VARCHAR2(200),
            STATUS VARCHAR2(30) DEFAULT ''WAITING'' NOT NULL,
            CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
            UPDATED_AT DATE
        )';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'USER_ID';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (USER_ID NUMBER NULL)'; END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'INQUIRY_TYPE';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (INQUIRY_TYPE VARCHAR2(30) DEFAULT ''etc'' NOT NULL)'; END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'TITLE';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (TITLE VARCHAR2(200) DEFAULT ''inquiry'' NOT NULL)'; END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'CONTENT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (CONTENT CLOB)'; END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'REPLY_EMAIL';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (REPLY_EMAIL VARCHAR2(200))'; END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'STATUS';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (STATUS VARCHAR2(30) DEFAULT ''WAITING'' NOT NULL)'; END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'CREATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (CREATED_AT DATE DEFAULT SYSDATE NOT NULL)'; END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INQUIRIES' AND COLUMN_NAME = 'UPDATED_AT';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE INQUIRIES ADD (UPDATED_AT DATE)'; END IF;

    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_INQUIRIES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_INQUIRIES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    END IF;
END;
/

COMMIT;