CREATE TABLE INQUIRIES (
    INQUIRY_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NULL,
    INQUIRY_TYPE VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    REPLY_EMAIL VARCHAR2(200),
    STATUS VARCHAR2(30) DEFAULT 'WAITING' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    CONSTRAINT FK_INQUIRIES_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE SEQUENCE SEQ_INQUIRIES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

COMMENT ON TABLE INQUIRIES IS '사용자 문의';
COMMENT ON COLUMN INQUIRIES.INQUIRY_TYPE IS 'lost, found, match, report, etc';
COMMENT ON COLUMN INQUIRIES.STATUS IS 'WAITING, ANSWERED, CLOSED, DELETED';
