SET DEFINE OFF;
-- FindCampus storage place reset for found-item handover.
-- Department office phone numbers are based on Dongmyong University department office contact notice.

UPDATE STORAGE_PLACES
   SET USE_YN = 'D'
 WHERE STORAGE_NAME NOT IN (
        '학생복지관 2층 학생·장학봉사팀',
        '중앙도서관 안내데스크(1층 데스크)',
        '대학본관 1층',
        '학과사무실 - 반려동물산업학부/식품영양학과',
        '학과사무실 - 상담·임상심리학과',
        '학과사무실 - 언어치료청각재활학과',
        '학과사무실 - 간호학과',
        '학과사무실 - 응급구조학과',
        '학과사무실 - 사회복지학과',
        '학과사무실 - 유아교육과',
        '학과사무실 - 작업치료학과',
        '학과사무실 - 스포츠재활학과',
        '학과사무실 - 애견미용·행동교정학과',
        '학과사무실 - 반려동물보건학과',
        '학과사무실 - 뷰티케어학과',
        '학과사무실 - 패션디자인학과',
        '학과사무실 - 헤어디자인학과/메이크업디자인학과',
        '학과사무실 - 컴퓨터공학과/의료기기학과/전자 및 의용공학과',
        '학과사무실 - 게임그래픽학과/정보보호학과',
        '학과사무실 - 디지털콘텐츠학과',
        '학과사무실 - 소프트웨어학과/AI학부/미래자동차학과/자동차공학과',
        '학과사무실 - 항만물류시스템학과',
        '학과사무실 - 냉동공조공학과',
        '학과사무실 - 게임공학과',
        '학과사무실 - 전기제어학부/전기에너지전공/전기공학과/조선해양공학과/해양모빌리티학과',
        '학과사무실 - 기계로봇공학과',
        '학과사무실 - 실내건축학과',
        '학과사무실 - 건축공학과',
        '학과사무실 - 건축학과',
        '학과사무실 - 시각디자인학과',
        '학과사무실 - 국제통상물류학과/글로벌비즈니스학과/글로벌무역통상전공/글로벌금융회계전공',
        '학과사무실 - 호텔조리베이커리학과/항공서비스학과',
        '학과사무실 - 글로벌관광학과/호텔관광학과/호텔경영전공/관광경영전공',
        '학과사무실 - 경영학과',
        '학과사무실 - 유통물류학과/유통경영전공/국제물류전공/국제물류전공(2+2)',
        '학과사무실 - 웹툰·애니메이션학과',
        '학과사무실 - 미디어커뮤니케이션학과',
        '학과사무실 - 광고홍보학과',
        '학과사무실 - 글로벌문화콘텐츠학과',
        '학과사무실 - K-sports 태권도학과',
        '학과사무실 - 군사학과/레저·승마학과',
        '학과사무실 - 엔터테인먼트예술학과/축구학과/Do-ing학부',
        '학과사무실 - 동양문화학과',
        '학과사무실 - 선명상치유학과',
        '학과사무실 - 복지경영학과',
        '학과사무실 - 창업학과',
        '학과사무실 - 한국어교육다문화학과',
        '학과사무실 - Dept. of Global Korean Studies',
        '학과사무실 - Dept. of Global Business',
        '학과사무실 - Dept. of AI and Computer Engineering',
        '학과사무실 - Dept. of Mechanical and Automotive Engineering',
        '학과사무실 - Dept. of Information System and Security',
        '학과사무실 - Dept. of Tech Management and Innovation',
        '학과사무실 - Dept. of Culture and Design Management'
     );

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학생복지관 2층 학생·장학봉사팀' AS STORAGE_NAME,
        (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE USE_YN = 'Y' AND (LOCATION_NAME = '8. 학생복지관' OR REGEXP_REPLACE(LOCATION_NAME, '^[0-9]+\.\s*', '') = '학생복지관')) AS LOCATION_ID,
        '학생·장학봉사팀' AS MANAGER_NAME,
        '051-629-0514' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학생복지관 2층 학생·장학봉사팀에서 본인 확인 후 수령합니다.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '중앙도서관 안내데스크(1층 데스크)' AS STORAGE_NAME,
        (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE USE_YN = 'Y' AND (LOCATION_NAME = '10. 중앙도서관' OR REGEXP_REPLACE(LOCATION_NAME, '^[0-9]+\.\s*', '') = '중앙도서관')) AS LOCATION_ID,
        '중앙도서관 1층 데스크' AS MANAGER_NAME,
        '051-629-3118' AS PHONE,
        '평일 09:00 ~ 21:00' AS OPERATING_HOURS,
        '중앙도서관 1층 데스크에서 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '대학본관 1층' AS STORAGE_NAME,
        (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE USE_YN = 'Y' AND (LOCATION_NAME = '1. 대학본관' OR REGEXP_REPLACE(LOCATION_NAME, '^[0-9]+\.\s*', '') = '대학본관')) AS LOCATION_ID,
        '대학본관 안내' AS MANAGER_NAME,
        '051-629-1000' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '대학본관 1층에서 안내에 따라 수령 절차를 진행합니다.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 반려동물산업학부/식품영양학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2227' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 상담·임상심리학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2661' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 언어치료청각재활학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2136' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 간호학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2012, 2671' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 응급구조학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2351' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 사회복지학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2111' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 유아교육과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2141' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 작업치료학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2015' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 스포츠재활학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2081' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 애견미용·행동교정학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2226' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 반려동물보건학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2224' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 뷰티케어학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2305' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 패션디자인학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2291' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 헤어디자인학과/메이크업디자인학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2306' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 컴퓨터공학과/의료기기학과/전자 및 의용공학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1161' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 게임그래픽학과/정보보호학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1271' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 디지털콘텐츠학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1201' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 소프트웨어학과/AI학부/미래자동차학과/자동차공학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1131' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 항만물류시스템학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1414' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 냉동공조공학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1671' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 게임공학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1241' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 전기제어학부/전기에너지전공/전기공학과/조선해양공학과/해양모빌리티학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1301' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 기계로봇공학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1410' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 실내건축학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2481' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 건축공학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2451' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 건축학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2421' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 시각디자인학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2231' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 국제통상물류학과/글로벌비즈니스학과/글로벌무역통상전공/글로벌금융회계전공' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1851' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 호텔조리베이커리학과/항공서비스학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1911' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 글로벌관광학과/호텔관광학과/호텔경영전공/관광경영전공' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1841' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 경영학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1941' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 유통물류학과/유통경영전공/국제물류전공/국제물류전공(2+2)' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-1931' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 웹툰·애니메이션학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2613' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 미디어커뮤니케이션학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2021' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 광고홍보학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2051' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 글로벌문화콘텐츠학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2513' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - K-sports 태권도학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2614, 2642' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 군사학과/레저·승마학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2611' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 엔터테인먼트예술학과/축구학과/Do-ing학부' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-2612' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 동양문화학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3411' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 선명상치유학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3413' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 복지경영학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3414' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 창업학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3417' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - 한국어교육다문화학과' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3415' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - Dept. of Global Korean Studies' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3066' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - Dept. of Global Business' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3065' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - Dept. of AI and Computer Engineering' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3065' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - Dept. of Mechanical and Automotive Engineering' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3067' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - Dept. of Information System and Security' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3067' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - Dept. of Tech Management and Innovation' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3066' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

MERGE INTO STORAGE_PLACES S
USING (
    SELECT
        '학과사무실 - Dept. of Culture and Design Management' AS STORAGE_NAME,
        NULL AS LOCATION_ID,
        '학과사무실' AS MANAGER_NAME,
        '051-629-3066' AS PHONE,
        '평일 09:00 ~ 17:00' AS OPERATING_HOURS,
        '학과사무실 보관 물품입니다. 방문 전 연락처로 보관 여부를 확인해 주세요.' AS DESCRIPTION
    FROM DUAL
) SRC
ON (S.STORAGE_NAME = SRC.STORAGE_NAME)
WHEN MATCHED THEN
    UPDATE SET
        S.LOCATION_ID = SRC.LOCATION_ID,
        S.MANAGER_NAME = SRC.MANAGER_NAME,
        S.PHONE = SRC.PHONE,
        S.OPERATING_HOURS = SRC.OPERATING_HOURS,
        S.DESCRIPTION = SRC.DESCRIPTION,
        S.USE_YN = 'Y'
WHEN NOT MATCHED THEN
    INSERT (STORAGE_ID, STORAGE_NAME, LOCATION_ID, MANAGER_NAME, PHONE, OPERATING_HOURS, DESCRIPTION, USE_YN, CREATED_AT)
    VALUES ((SELECT NVL(MAX(STORAGE_ID), 0) + 1 FROM STORAGE_PLACES), SRC.STORAGE_NAME, SRC.LOCATION_ID, SRC.MANAGER_NAME, SRC.PHONE, SRC.OPERATING_HOURS, SRC.DESCRIPTION, 'Y', SYSDATE);

-- Move old student support center records to the official student welfare center handover place.
UPDATE FOUND_ITEMS F
   SET STORAGE_ID = (
       SELECT MIN(STORAGE_ID)
         FROM STORAGE_PLACES
        WHERE STORAGE_NAME = '학생복지관 2층 학생·장학봉사팀'
   )
 WHERE F.STORAGE_ID IN (
       SELECT STORAGE_ID
         FROM STORAGE_PLACES
        WHERE STORAGE_NAME IN ('학생장학봉사팀 분실물 센터', '학생장학봉사팀', '학생복지관 보관소')
           OR STORAGE_NAME LIKE '%학생장학봉사팀%'
           OR STORAGE_NAME LIKE '%학생복지관%'
 );

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID)
                        FROM LOCATIONS
                       WHERE USE_YN = 'Y'
                         AND (LOCATION_NAME = '8. 학생복지관'
                              OR REGEXP_REPLACE(LOCATION_NAME, '^[0-9]+\.\s*', '') = '학생복지관')),
       MANAGER_NAME = '학생·장학봉사팀',
       PHONE = '051-629-0514',
       OPERATING_HOURS = '평일 09:00 ~ 17:00',
       DESCRIPTION = '학생복지관 2층 학생·장학봉사팀에서 본인 확인 후 수령합니다.',
       USE_YN = 'Y'
 WHERE STORAGE_NAME = '학생복지관 2층 학생·장학봉사팀';

UPDATE STORAGE_PLACES
   SET USE_YN = 'D'
 WHERE (STORAGE_NAME IN ('학생장학봉사팀 분실물 센터', '학생장학봉사팀', '학생복지관 보관소')
        OR STORAGE_NAME LIKE '%학생장학봉사팀%')
   AND STORAGE_NAME <> '학생복지관 2층 학생·장학봉사팀';

COMMIT;
