-- FindCampus campus map coordinate update
-- Location names are preserved. Only LATITUDE/LONGITUDE are updated.
-- Coordinates are centered by the official TU campus map building positions.

MERGE INTO LOCATIONS L
USING (SELECT '대학본관' LOCATION_NAME, 35.12375 LATITUDE, 129.09862 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '보건복지관' LOCATION_NAME, 35.12350 LATITUDE, 129.09925 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '건축디자인관' LOCATION_NAME, 35.12258 LATITUDE, 129.09845 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '대학원' LOCATION_NAME, 35.12278 LATITUDE, 129.09972 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '건축공학실습동' LOCATION_NAME, 35.12078 LATITUDE, 129.09738 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '학생회관' LOCATION_NAME, 35.12045 LATITUDE, 129.09762 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명스터디움' LOCATION_NAME, 35.12062 LATITUDE, 129.09845 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명스타디움' LOCATION_NAME, 35.12062 LATITUDE, 129.09845 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '학생복지관' LOCATION_NAME, 35.12393 LATITUDE, 129.10042 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명생활관 (2호관)' LOCATION_NAME, 35.12436 LATITUDE, 129.10002 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명생활관(2호관)' LOCATION_NAME, 35.12436 LATITUDE, 129.10002 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '중앙도서관' LOCATION_NAME, 35.12462 LATITUDE, 129.10082 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명관' LOCATION_NAME, 35.12510 LATITUDE, 129.10285 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '반려동물관' LOCATION_NAME, 35.12460 LATITUDE, 129.10330 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT 'ICT 2관' LOCATION_NAME, 35.12355 LATITUDE, 129.10382 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT 'ICT2관' LOCATION_NAME, 35.12355 LATITUDE, 129.10382 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT 'ICT 3관' LOCATION_NAME, 35.12278 LATITUDE, 129.10392 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT 'ICT3관' LOCATION_NAME, 35.12278 LATITUDE, 129.10392 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT 'ICT 1관' LOCATION_NAME, 35.12458 LATITUDE, 129.10205 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT 'ICT1관' LOCATION_NAME, 35.12458 LATITUDE, 129.10205 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '교수연구동' LOCATION_NAME, 35.12386 LATITUDE, 129.10212 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '국제대학관' LOCATION_NAME, 35.12338 LATITUDE, 129.10232 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명공업고등학교' LOCATION_NAME, 35.12178 LATITUDE, 129.10305 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT 'Busan International College Office' LOCATION_NAME, 35.12352 LATITUDE, 129.10262 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '국제대학 본관' LOCATION_NAME, 35.12352 LATITUDE, 129.10262 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '쉼터' LOCATION_NAME, 35.12305 LATITUDE, 129.10208 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '국제산학협력관' LOCATION_NAME, 35.12103 LATITUDE, 129.10408 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '가온누리' LOCATION_NAME, 35.12282 LATITUDE, 129.10052 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '선당' LOCATION_NAME, 35.12528 LATITUDE, 129.10158 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT 'Do-ing관' LOCATION_NAME, 35.12073 LATITUDE, 129.09920 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '창의인재관' LOCATION_NAME, 35.12073 LATITUDE, 129.09920 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '봉사관' LOCATION_NAME, 35.12402 LATITUDE, 129.09992 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '분수대' LOCATION_NAME, 35.12382 LATITUDE, 129.09955 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '용마광장' LOCATION_NAME, 35.12376 LATITUDE, 129.10258 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '제1정문' LOCATION_NAME, 35.12028 LATITUDE, 129.10052 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '제2정문' LOCATION_NAME, 35.12050 LATITUDE, 129.10442 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '제3정문' LOCATION_NAME, 35.12186 LATITUDE, 129.10472 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '제1주차장' LOCATION_NAME, 35.12036 LATITUDE, 129.09818 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '제2주차장' LOCATION_NAME, 35.12062 LATITUDE, 129.10190 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '제3주차장' LOCATION_NAME, 35.12158 LATITUDE, 129.10110 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '제5주차장' LOCATION_NAME, 35.12405 LATITUDE, 129.10485 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '대운동장 1' LOCATION_NAME, 35.12350 LATITUDE, 129.10115 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '대운동장1' LOCATION_NAME, 35.12350 LATITUDE, 129.10115 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '대운동장 2' LOCATION_NAME, 35.12150 LATITUDE, 129.10128 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '대운동장2' LOCATION_NAME, 35.12150 LATITUDE, 129.10128 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '원형광장' LOCATION_NAME, 35.12212 LATITUDE, 129.09910 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '주차관제소' LOCATION_NAME, 35.12102 LATITUDE, 129.10042 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '주차관리소' LOCATION_NAME, 35.12102 LATITUDE, 129.10042 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '종합체육시설' LOCATION_NAME, 35.12146 LATITUDE, 129.10155 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '순환버스 정류장' LOCATION_NAME, 35.12244 LATITUDE, 129.10150 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '순환버스정류장' LOCATION_NAME, 35.12244 LATITUDE, 129.10150 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '마지뜨락' LOCATION_NAME, 35.12042 LATITUDE, 129.10205 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '학생휴게점(cafe)' LOCATION_NAME, 35.12286 LATITUDE, 129.09936 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명생활관 (1호관)' LOCATION_NAME, 35.12602 LATITUDE, 129.10278 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명생활관(1호관)' LOCATION_NAME, 35.12602 LATITUDE, 129.10278 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '동명뜰' LOCATION_NAME, 35.12496 LATITUDE, 129.10038 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '체육시설관리동' LOCATION_NAME, 35.12172 LATITUDE, 129.10208 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '그린스타트업타운' LOCATION_NAME, 35.12358 LATITUDE, 129.10503 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '대학동물병원' LOCATION_NAME, 35.12470 LATITUDE, 129.10425 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '대학동명병원' LOCATION_NAME, 35.12470 LATITUDE, 129.10425 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

MERGE INTO LOCATIONS L
USING (SELECT '창업거점지구' LOCATION_NAME, 35.12462 LATITUDE, 129.10562 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

COMMIT;

SELECT LOCATION_NAME, LATITUDE, LONGITUDE
  FROM LOCATIONS
 WHERE USE_YN = 'Y'
 ORDER BY LOCATION_NAME;
