-- FindCampus campus location numbering and coordinate update
-- Run this once in Oracle SQL Developer with the application schema.
-- Existing location names are renamed to numbered names, and coordinates are updated.

-- 1. 대학본관
UPDATE LOCATIONS
   SET LOCATION_NAME = '1. 대학본관',
       BUILDING_NAME = '1. 대학본관',
       DETAIL = '1. 대학본관',
       LATITUDE = 35.12337821045975,
       LONGITUDE = 129.1026809933428,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('1. 대학본관', '대학본관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '1. 대학본관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '1. 대학본관' LOCATION_NAME, 35.12337821045975 LATITUDE, 129.1026809933428 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '1. 대학본관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학본관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '1. 대학본관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학본관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '1. 대학본관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학본관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('대학본관');

-- 2. 보건복지관
UPDATE LOCATIONS
   SET LOCATION_NAME = '2. 보건복지관',
       BUILDING_NAME = '2. 보건복지관',
       DETAIL = '2. 보건복지관',
       LATITUDE = 35.12266204615481,
       LONGITUDE = 129.1029258175948,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('2. 보건복지관', '보건복지관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '2. 보건복지관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '2. 보건복지관' LOCATION_NAME, 35.12266204615481 LATITUDE, 129.1029258175948 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '2. 보건복지관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('보건복지관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '2. 보건복지관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('보건복지관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '2. 보건복지관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('보건복지관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('보건복지관');

-- 3. 건축디자인관
UPDATE LOCATIONS
   SET LOCATION_NAME = '3. 건축디자인관',
       BUILDING_NAME = '3. 건축디자인관',
       DETAIL = '3. 건축디자인관',
       LATITUDE = 35.12415182748975,
       LONGITUDE = 129.10211133214523,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('3. 건축디자인관', '건축디자인관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '3. 건축디자인관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '3. 건축디자인관' LOCATION_NAME, 35.12415182748975 LATITUDE, 129.10211133214523 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '3. 건축디자인관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('건축디자인관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '3. 건축디자인관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('건축디자인관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '3. 건축디자인관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('건축디자인관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('건축디자인관');

-- 4. 대학원
UPDATE LOCATIONS
   SET LOCATION_NAME = '4. 대학원',
       BUILDING_NAME = '4. 대학원',
       DETAIL = '4. 대학원',
       LATITUDE = 35.122849458973796,
       LONGITUDE = 129.10238222518637,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('4. 대학원', '대학원')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '4. 대학원'
   );

MERGE INTO LOCATIONS L
USING (SELECT '4. 대학원' LOCATION_NAME, 35.122849458973796 LATITUDE, 129.10238222518637 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '4. 대학원')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학원'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '4. 대학원')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학원'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '4. 대학원')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학원'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('대학원');

-- 5. 건축공학실습동
UPDATE LOCATIONS
   SET LOCATION_NAME = '5. 건축공학실습동',
       BUILDING_NAME = '5. 건축공학실습동',
       DETAIL = '5. 건축공학실습동',
       LATITUDE = 35.12477548599242,
       LONGITUDE = 129.10161458626692,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('5. 건축공학실습동', '건축공학실습동', '건축학습동')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '5. 건축공학실습동'
   );

MERGE INTO LOCATIONS L
USING (SELECT '5. 건축공학실습동' LOCATION_NAME, 35.12477548599242 LATITUDE, 129.10161458626692 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '5. 건축공학실습동')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('건축공학실습동', '건축학습동'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '5. 건축공학실습동')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('건축공학실습동', '건축학습동'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '5. 건축공학실습동')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('건축공학실습동', '건축학습동'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('건축공학실습동', '건축학습동');

-- 6. 학생회관
UPDATE LOCATIONS
   SET LOCATION_NAME = '6. 학생회관',
       BUILDING_NAME = '6. 학생회관',
       DETAIL = '6. 학생회관',
       LATITUDE = 35.12467823956183,
       LONGITUDE = 129.10137626495128,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('6. 학생회관', '학생회관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '6. 학생회관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '6. 학생회관' LOCATION_NAME, 35.12467823956183 LATITUDE, 129.10137626495128 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '6. 학생회관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생회관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '6. 학생회관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생회관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '6. 학생회관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생회관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('학생회관');

-- 7. 동명스타디움
UPDATE LOCATIONS
   SET LOCATION_NAME = '7. 동명스타디움',
       BUILDING_NAME = '7. 동명스타디움',
       DETAIL = '7. 동명스타디움',
       LATITUDE = 35.124317871654185,
       LONGITUDE = 129.10124086821125,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('7. 동명스타디움', '동명스타디움', '동명스터디움')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '7. 동명스타디움'
   );

MERGE INTO LOCATIONS L
USING (SELECT '7. 동명스타디움' LOCATION_NAME, 35.124317871654185 LATITUDE, 129.10124086821125 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '7. 동명스타디움')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명스타디움', '동명스터디움'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '7. 동명스타디움')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명스타디움', '동명스터디움'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '7. 동명스타디움')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명스타디움', '동명스터디움'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('동명스타디움', '동명스터디움');

-- 8. 학생복지관
UPDATE LOCATIONS
   SET LOCATION_NAME = '8. 학생복지관',
       BUILDING_NAME = '8. 학생복지관',
       DETAIL = '8. 학생복지관',
       LATITUDE = 35.12171815499319,
       LONGITUDE = 129.1031812340018,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('8. 학생복지관', '학생복지관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '8. 학생복지관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '8. 학생복지관' LOCATION_NAME, 35.12171815499319 LATITUDE, 129.1031812340018 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '8. 학생복지관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생복지관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '8. 학생복지관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생복지관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '8. 학생복지관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생복지관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('학생복지관');

-- 9. 동명생활관 (2호관)
UPDATE LOCATIONS
   SET LOCATION_NAME = '9. 동명생활관 (2호관)',
       BUILDING_NAME = '9. 동명생활관 (2호관)',
       DETAIL = '9. 동명생활관 (2호관)',
       LATITUDE = 35.121989459867514,
       LONGITUDE = 129.10338563661972,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('9. 동명생활관 (2호관)', '동명생활관 (2호관)', '동명생활관(2호관)')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '9. 동명생활관 (2호관)'
   );

MERGE INTO LOCATIONS L
USING (SELECT '9. 동명생활관 (2호관)' LOCATION_NAME, 35.121989459867514 LATITUDE, 129.10338563661972 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '9. 동명생활관 (2호관)')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명생활관 (2호관)', '동명생활관(2호관)'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '9. 동명생활관 (2호관)')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명생활관 (2호관)', '동명생활관(2호관)'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '9. 동명생활관 (2호관)')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명생활관 (2호관)', '동명생활관(2호관)'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('동명생활관 (2호관)', '동명생활관(2호관)');

-- 10. 중앙도서관
UPDATE LOCATIONS
   SET LOCATION_NAME = '10. 중앙도서관',
       BUILDING_NAME = '10. 중앙도서관',
       DETAIL = '10. 중앙도서관',
       LATITUDE = 35.120967560709644,
       LONGITUDE = 129.1035924257535,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('10. 중앙도서관', '중앙도서관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '10. 중앙도서관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '10. 중앙도서관' LOCATION_NAME, 35.120967560709644 LATITUDE, 129.1035924257535 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '10. 중앙도서관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('중앙도서관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '10. 중앙도서관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('중앙도서관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '10. 중앙도서관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('중앙도서관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('중앙도서관');

-- 11. 동명관
UPDATE LOCATIONS
   SET LOCATION_NAME = '11. 동명관',
       BUILDING_NAME = '11. 동명관',
       DETAIL = '11. 동명관',
       LATITUDE = 35.11949073313119,
       LONGITUDE = 129.1030115393665,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('11. 동명관', '동명관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '11. 동명관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '11. 동명관' LOCATION_NAME, 35.11949073313119 LATITUDE, 129.1030115393665 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '11. 동명관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '11. 동명관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '11. 동명관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('동명관');

-- 12. 반려동물관
UPDATE LOCATIONS
   SET LOCATION_NAME = '12. 반려동물관',
       BUILDING_NAME = '12. 반려동물관',
       DETAIL = '12. 반려동물관',
       LATITUDE = 35.119655070168506,
       LONGITUDE = 129.10223979292653,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('12. 반려동물관', '반려동물관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '12. 반려동물관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '12. 반려동물관' LOCATION_NAME, 35.119655070168506 LATITUDE, 129.10223979292653 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '12. 반려동물관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('반려동물관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '12. 반려동물관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('반려동물관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '12. 반려동물관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('반려동물관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('반려동물관');

-- 13. ICT 2관
UPDATE LOCATIONS
   SET LOCATION_NAME = '13. ICT 2관',
       BUILDING_NAME = '13. ICT 2관',
       DETAIL = '13. ICT 2관',
       LATITUDE = 35.11984777380266,
       LONGITUDE = 129.10152086924418,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('13. ICT 2관', 'ICT 2관', 'ICT2관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '13. ICT 2관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '13. ICT 2관' LOCATION_NAME, 35.11984777380266 LATITUDE, 129.10152086924418 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '13. ICT 2관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 2관', 'ICT2관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '13. ICT 2관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 2관', 'ICT2관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '13. ICT 2관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 2관', 'ICT2관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('ICT 2관', 'ICT2관');

-- 14. ICT 3관
UPDATE LOCATIONS
   SET LOCATION_NAME = '14. ICT 3관',
       BUILDING_NAME = '14. ICT 3관',
       DETAIL = '14. ICT 3관',
       LATITUDE = 35.12002793069155,
       LONGITUDE = 129.10087565282856,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('14. ICT 3관', 'ICT 3관', 'ICT3관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '14. ICT 3관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '14. ICT 3관' LOCATION_NAME, 35.12002793069155 LATITUDE, 129.10087565282856 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '14. ICT 3관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 3관', 'ICT3관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '14. ICT 3관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 3관', 'ICT3관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '14. ICT 3관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 3관', 'ICT3관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('ICT 3관', 'ICT3관');

-- 15. ICT 1관
UPDATE LOCATIONS
   SET LOCATION_NAME = '15. ICT 1관',
       BUILDING_NAME = '15. ICT 1관',
       DETAIL = '15. ICT 1관',
       LATITUDE = 35.12013551953265,
       LONGITUDE = 129.1032447328397,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('15. ICT 1관', 'ICT 1관', 'ICT1관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '15. ICT 1관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '15. ICT 1관' LOCATION_NAME, 35.12013551953265 LATITUDE, 129.1032447328397 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '15. ICT 1관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 1관', 'ICT1관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '15. ICT 1관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 1관', 'ICT1관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '15. ICT 1관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('ICT 1관', 'ICT1관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('ICT 1관', 'ICT1관');

-- 16. 교수연구동
UPDATE LOCATIONS
   SET LOCATION_NAME = '16. 교수연구동',
       BUILDING_NAME = '16. 교수연구동',
       DETAIL = '16. 교수연구동',
       LATITUDE = 35.120486163453464,
       LONGITUDE = 129.1026422885578,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('16. 교수연구동', '교수연구동')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '16. 교수연구동'
   );

MERGE INTO LOCATIONS L
USING (SELECT '16. 교수연구동' LOCATION_NAME, 35.120486163453464 LATITUDE, 129.1026422885578 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '16. 교수연구동')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('교수연구동'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '16. 교수연구동')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('교수연구동'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '16. 교수연구동')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('교수연구동'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('교수연구동');

-- 17. 국제대학관
UPDATE LOCATIONS
   SET LOCATION_NAME = '17. 국제대학관',
       BUILDING_NAME = '17. 국제대학관',
       DETAIL = '17. 국제대학관',
       LATITUDE = 35.12050349007318,
       LONGITUDE = 129.10177352689968,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('17. 국제대학관', '국제대학관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '17. 국제대학관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '17. 국제대학관' LOCATION_NAME, 35.12050349007318 LATITUDE, 129.10177352689968 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '17. 국제대학관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제대학관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '17. 국제대학관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제대학관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '17. 국제대학관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제대학관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('국제대학관');

-- 18. 동명공업고등학교
UPDATE LOCATIONS
   SET LOCATION_NAME = '18. 동명공업고등학교',
       BUILDING_NAME = '18. 동명공업고등학교',
       DETAIL = '18. 동명공업고등학교',
       LATITUDE = 35.121003077811075,
       LONGITUDE = 129.100766342436,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('18. 동명공업고등학교', '동명공업고등학교')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '18. 동명공업고등학교'
   );

MERGE INTO LOCATIONS L
USING (SELECT '18. 동명공업고등학교' LOCATION_NAME, 35.121003077811075 LATITUDE, 129.100766342436 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '18. 동명공업고등학교')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명공업고등학교'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '18. 동명공업고등학교')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명공업고등학교'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '18. 동명공업고등학교')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명공업고등학교'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('동명공업고등학교');

-- 19. 국제대학 본관
UPDATE LOCATIONS
   SET LOCATION_NAME = '19. 국제대학 본관',
       BUILDING_NAME = '19. 국제대학 본관',
       DETAIL = '19. 국제대학 본관',
       LATITUDE = 35.12027741458532,
       LONGITUDE = 129.1019486876352,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('19. 국제대학 본관', '국제대학 본관', 'Busan International College Office')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '19. 국제대학 본관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '19. 국제대학 본관' LOCATION_NAME, 35.12027741458532 LATITUDE, 129.1019486876352 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '19. 국제대학 본관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제대학 본관', 'Busan International College Office'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '19. 국제대학 본관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제대학 본관', 'Busan International College Office'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '19. 국제대학 본관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제대학 본관', 'Busan International College Office'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('국제대학 본관', 'Busan International College Office');

-- 20. 쉼터(편의점)
UPDATE LOCATIONS
   SET LOCATION_NAME = '20. 쉼터(편의점)',
       BUILDING_NAME = '20. 쉼터(편의점)',
       DETAIL = '20. 쉼터(편의점)',
       LATITUDE = 35.12065954014353,
       LONGITUDE = 129.10212851076417,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('20. 쉼터(편의점)', '쉼터(편의점)', '쉼터')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '20. 쉼터(편의점)'
   );

MERGE INTO LOCATIONS L
USING (SELECT '20. 쉼터(편의점)' LOCATION_NAME, 35.12065954014353 LATITUDE, 129.10212851076417 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '20. 쉼터(편의점)')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('쉼터(편의점)', '쉼터'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '20. 쉼터(편의점)')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('쉼터(편의점)', '쉼터'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '20. 쉼터(편의점)')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('쉼터(편의점)', '쉼터'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('쉼터(편의점)', '쉼터');

-- 21. 국제산학협력관(학생군사관)
UPDATE LOCATIONS
   SET LOCATION_NAME = '21. 국제산학협력관(학생군사관)',
       BUILDING_NAME = '21. 국제산학협력관(학생군사관)',
       DETAIL = '21. 국제산학협력관(학생군사관)',
       LATITUDE = 35.121015943570036,
       LONGITUDE = 129.09963422830856,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('21. 국제산학협력관(학생군사관)', '국제산학협력관(학생군사관)', '국제산학협력관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '21. 국제산학협력관(학생군사관)'
   );

MERGE INTO LOCATIONS L
USING (SELECT '21. 국제산학협력관(학생군사관)' LOCATION_NAME, 35.121015943570036 LATITUDE, 129.09963422830856 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '21. 국제산학협력관(학생군사관)')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제산학협력관(학생군사관)', '국제산학협력관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '21. 국제산학협력관(학생군사관)')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제산학협력관(학생군사관)', '국제산학협력관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '21. 국제산학협력관(학생군사관)')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('국제산학협력관(학생군사관)', '국제산학협력관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('국제산학협력관(학생군사관)', '국제산학협력관');

-- 22. 가온누리(학생휴게점)
UPDATE LOCATIONS
   SET LOCATION_NAME = '22. 가온누리(학생휴게점)',
       BUILDING_NAME = '22. 가온누리(학생휴게점)',
       DETAIL = '22. 가온누리(학생휴게점)',
       LATITUDE = 35.12200155868467,
       LONGITUDE = 129.10242897998995,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('22. 가온누리(학생휴게점)', '가온누리(학생휴게점)', '가온누리')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '22. 가온누리(학생휴게점)'
   );

MERGE INTO LOCATIONS L
USING (SELECT '22. 가온누리(학생휴게점)' LOCATION_NAME, 35.12200155868467 LATITUDE, 129.10242897998995 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '22. 가온누리(학생휴게점)')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('가온누리(학생휴게점)', '가온누리'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '22. 가온누리(학생휴게점)')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('가온누리(학생휴게점)', '가온누리'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '22. 가온누리(학생휴게점)')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('가온누리(학생휴게점)', '가온누리'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('가온누리(학생휴게점)', '가온누리');

-- 23. 선당
UPDATE LOCATIONS
   SET LOCATION_NAME = '23. 선당',
       BUILDING_NAME = '23. 선당',
       DETAIL = '23. 선당',
       LATITUDE = 35.12019769767011,
       LONGITUDE = 129.10394553330747,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('23. 선당', '선당')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '23. 선당'
   );

MERGE INTO LOCATIONS L
USING (SELECT '23. 선당' LOCATION_NAME, 35.12019769767011 LATITUDE, 129.10394553330747 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '23. 선당')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('선당'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '23. 선당')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('선당'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '23. 선당')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('선당'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('선당');

-- 24. 창의인재관
UPDATE LOCATIONS
   SET LOCATION_NAME = '24. 창의인재관',
       BUILDING_NAME = '24. 창의인재관',
       DETAIL = '24. 창의인재관',
       LATITUDE = 35.12375187348464,
       LONGITUDE = 129.1015306975554,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('24. 창의인재관', '창의인재관', 'Do-ing관')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '24. 창의인재관'
   );

MERGE INTO LOCATIONS L
USING (SELECT '24. 창의인재관' LOCATION_NAME, 35.12375187348464 LATITUDE, 129.1015306975554 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '24. 창의인재관')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('창의인재관', 'Do-ing관'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '24. 창의인재관')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('창의인재관', 'Do-ing관'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '24. 창의인재관')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('창의인재관', 'Do-ing관'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('창의인재관', 'Do-ing관');

-- 25. 분수대
UPDATE LOCATIONS
   SET LOCATION_NAME = '25. 분수대',
       BUILDING_NAME = '25. 분수대',
       DETAIL = '25. 분수대',
       LATITUDE = 35.12230637424442,
       LONGITUDE = 129.10316893988448,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('25. 분수대')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '25. 분수대'
   );

MERGE INTO LOCATIONS L
USING (SELECT '25. 분수대' LOCATION_NAME, 35.12230637424442 LATITUDE, 129.10316893988448 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

-- 26. 용마광장
UPDATE LOCATIONS
   SET LOCATION_NAME = '26. 용마광장',
       BUILDING_NAME = '26. 용마광장',
       DETAIL = '26. 용마광장',
       LATITUDE = 35.12018669289543,
       LONGITUDE = 129.1025029756337,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('26. 용마광장', '용마광장')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '26. 용마광장'
   );

MERGE INTO LOCATIONS L
USING (SELECT '26. 용마광장' LOCATION_NAME, 35.12018669289543 LATITUDE, 129.1025029756337 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '26. 용마광장')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('용마광장'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '26. 용마광장')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('용마광장'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '26. 용마광장')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('용마광장'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('용마광장');

-- 27. 제1정문
UPDATE LOCATIONS
   SET LOCATION_NAME = '27. 제1정문',
       BUILDING_NAME = '27. 제1정문',
       DETAIL = '27. 제1정문',
       LATITUDE = 35.12296783333605,
       LONGITUDE = 129.10049324582604,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('27. 제1정문', '제1정문')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '27. 제1정문'
   );

MERGE INTO LOCATIONS L
USING (SELECT '27. 제1정문' LOCATION_NAME, 35.12296783333605 LATITUDE, 129.10049324582604 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '27. 제1정문')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제1정문'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '27. 제1정문')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제1정문'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '27. 제1정문')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제1정문'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('제1정문');

-- 28. 제2정문
UPDATE LOCATIONS
   SET LOCATION_NAME = '28. 제2정문',
       BUILDING_NAME = '28. 제2정문',
       DETAIL = '28. 제2정문',
       LATITUDE = 35.12163088160782,
       LONGITUDE = 129.09951017166344,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('28. 제2정문', '제2정문')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '28. 제2정문'
   );

MERGE INTO LOCATIONS L
USING (SELECT '28. 제2정문' LOCATION_NAME, 35.12163088160782 LATITUDE, 129.09951017166344 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '28. 제2정문')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제2정문'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '28. 제2정문')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제2정문'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '28. 제2정문')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제2정문'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('제2정문');

-- 29. 제3정문
UPDATE LOCATIONS
   SET LOCATION_NAME = '29. 제3정문',
       BUILDING_NAME = '29. 제3정문',
       DETAIL = '29. 제3정문',
       LATITUDE = 35.120413033884624,
       LONGITUDE = 129.10075392950841,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('29. 제3정문', '제3정문')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '29. 제3정문'
   );

MERGE INTO LOCATIONS L
USING (SELECT '29. 제3정문' LOCATION_NAME, 35.120413033884624 LATITUDE, 129.10075392950841 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '29. 제3정문')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제3정문'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '29. 제3정문')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제3정문'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '29. 제3정문')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제3정문'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('제3정문');

-- 30. 제1주차장
UPDATE LOCATIONS
   SET LOCATION_NAME = '30. 제1주차장',
       BUILDING_NAME = '30. 제1주차장',
       DETAIL = '30. 제1주차장',
       LATITUDE = 35.12353718960733,
       LONGITUDE = 129.10091918110075,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('30. 제1주차장', '제1주차장')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '30. 제1주차장'
   );

MERGE INTO LOCATIONS L
USING (SELECT '30. 제1주차장' LOCATION_NAME, 35.12353718960733 LATITUDE, 129.10091918110075 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '30. 제1주차장')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제1주차장'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '30. 제1주차장')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제1주차장'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '30. 제1주차장')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제1주차장'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('제1주차장');

-- 31. 제2주차장
UPDATE LOCATIONS
   SET LOCATION_NAME = '31. 제2주차장',
       BUILDING_NAME = '31. 제2주차장',
       DETAIL = '31. 제2주차장',
       LATITUDE = 35.122124370782196,
       LONGITUDE = 129.10041400069096,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('31. 제2주차장', '제2주차장')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '31. 제2주차장'
   );

MERGE INTO LOCATIONS L
USING (SELECT '31. 제2주차장' LOCATION_NAME, 35.122124370782196 LATITUDE, 129.10041400069096 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '31. 제2주차장')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제2주차장'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '31. 제2주차장')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제2주차장'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '31. 제2주차장')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제2주차장'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('제2주차장');

-- 32. 대운동장 1
UPDATE LOCATIONS
   SET LOCATION_NAME = '32. 대운동장 1',
       BUILDING_NAME = '32. 대운동장 1',
       DETAIL = '32. 대운동장 1',
       LATITUDE = 35.121183060785775,
       LONGITUDE = 129.10272875416405,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('32. 대운동장 1', '대운동장 1', '대운동장1')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '32. 대운동장 1'
   );

MERGE INTO LOCATIONS L
USING (SELECT '32. 대운동장 1' LOCATION_NAME, 35.121183060785775 LATITUDE, 129.10272875416405 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '32. 대운동장 1')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대운동장 1', '대운동장1'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '32. 대운동장 1')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대운동장 1', '대운동장1'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '32. 대운동장 1')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대운동장 1', '대운동장1'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('대운동장 1', '대운동장1');

-- 33. 대운동장 2
UPDATE LOCATIONS
   SET LOCATION_NAME = '33. 대운동장 2',
       BUILDING_NAME = '33. 대운동장 2',
       DETAIL = '33. 대운동장 2',
       LATITUDE = 35.12209421913468,
       LONGITUDE = 129.100983569105,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('33. 대운동장 2', '대운동장 2', '대운동장2')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '33. 대운동장 2'
   );

MERGE INTO LOCATIONS L
USING (SELECT '33. 대운동장 2' LOCATION_NAME, 35.12209421913468 LATITUDE, 129.100983569105 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '33. 대운동장 2')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대운동장 2', '대운동장2'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '33. 대운동장 2')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대운동장 2', '대운동장2'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '33. 대운동장 2')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대운동장 2', '대운동장2'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('대운동장 2', '대운동장2');

-- 34. 원형광장
UPDATE LOCATIONS
   SET LOCATION_NAME = '34. 원형광장',
       BUILDING_NAME = '34. 원형광장',
       DETAIL = '34. 원형광장',
       LATITUDE = 35.12325135616879,
       LONGITUDE = 129.10207173433406,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('34. 원형광장', '원형광장')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '34. 원형광장'
   );

MERGE INTO LOCATIONS L
USING (SELECT '34. 원형광장' LOCATION_NAME, 35.12325135616879 LATITUDE, 129.10207173433406 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '34. 원형광장')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('원형광장'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '34. 원형광장')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('원형광장'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '34. 원형광장')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('원형광장'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('원형광장');

-- 35. 주차관제소
UPDATE LOCATIONS
   SET LOCATION_NAME = '35. 주차관제소',
       BUILDING_NAME = '35. 주차관제소',
       DETAIL = '35. 주차관제소',
       LATITUDE = 35.122647763008146,
       LONGITUDE = 129.10141183864138,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('35. 주차관제소', '주차관제소', '주차관리소')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '35. 주차관제소'
   );

MERGE INTO LOCATIONS L
USING (SELECT '35. 주차관제소' LOCATION_NAME, 35.122647763008146 LATITUDE, 129.10141183864138 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '35. 주차관제소')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('주차관제소', '주차관리소'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '35. 주차관제소')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('주차관제소', '주차관리소'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '35. 주차관제소')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('주차관제소', '주차관리소'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('주차관제소', '주차관리소');

-- 36. 종합체육시설
UPDATE LOCATIONS
   SET LOCATION_NAME = '36. 종합체육시설',
       BUILDING_NAME = '36. 종합체육시설',
       DETAIL = '36. 종합체육시설',
       LATITUDE = 35.12154128733378,
       LONGITUDE = 129.1011695323422,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('36. 종합체육시설', '종합체육시설')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '36. 종합체육시설'
   );

MERGE INTO LOCATIONS L
USING (SELECT '36. 종합체육시설' LOCATION_NAME, 35.12154128733378 LATITUDE, 129.1011695323422 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '36. 종합체육시설')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('종합체육시설'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '36. 종합체육시설')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('종합체육시설'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '36. 종합체육시설')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('종합체육시설'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('종합체육시설');

-- 37. 제3주차장
UPDATE LOCATIONS
   SET LOCATION_NAME = '37. 제3주차장',
       BUILDING_NAME = '37. 제3주차장',
       DETAIL = '37. 제3주차장',
       LATITUDE = 35.12217796052198,
       LONGITUDE = 129.10161090425666,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('37. 제3주차장', '제3주차장')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '37. 제3주차장'
   );

MERGE INTO LOCATIONS L
USING (SELECT '37. 제3주차장' LOCATION_NAME, 35.12217796052198 LATITUDE, 129.10161090425666 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '37. 제3주차장')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제3주차장'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '37. 제3주차장')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제3주차장'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '37. 제3주차장')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제3주차장'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('제3주차장');

-- 38. 제5주차장
UPDATE LOCATIONS
   SET LOCATION_NAME = '38. 제5주차장',
       BUILDING_NAME = '38. 제5주차장',
       DETAIL = '38. 제5주차장',
       LATITUDE = 35.11919186666944,
       LONGITUDE = 129.10127917874257,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('38. 제5주차장', '제5주차장')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '38. 제5주차장'
   );

MERGE INTO LOCATIONS L
USING (SELECT '38. 제5주차장' LOCATION_NAME, 35.11919186666944 LATITUDE, 129.10127917874257 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '38. 제5주차장')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제5주차장'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '38. 제5주차장')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제5주차장'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '38. 제5주차장')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('제5주차장'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('제5주차장');

-- 39. 순환버스 정류장
UPDATE LOCATIONS
   SET LOCATION_NAME = '39. 순환버스 정류장',
       BUILDING_NAME = '39. 순환버스 정류장',
       DETAIL = '39. 순환버스 정류장',
       LATITUDE = 35.12156517771354,
       LONGITUDE = 129.10174048505553,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('39. 순환버스 정류장', '순환버스 정류장', '순환버스정류장')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '39. 순환버스 정류장'
   );

MERGE INTO LOCATIONS L
USING (SELECT '39. 순환버스 정류장' LOCATION_NAME, 35.12156517771354 LATITUDE, 129.10174048505553 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '39. 순환버스 정류장')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('순환버스 정류장', '순환버스정류장'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '39. 순환버스 정류장')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('순환버스 정류장', '순환버스정류장'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '39. 순환버스 정류장')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('순환버스 정류장', '순환버스정류장'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('순환버스 정류장', '순환버스정류장');

-- 40. 마지뜨락
UPDATE LOCATIONS
   SET LOCATION_NAME = '40. 마지뜨락',
       BUILDING_NAME = '40. 마지뜨락',
       DETAIL = '40. 마지뜨락',
       LATITUDE = 35.12222197234009,
       LONGITUDE = 129.10011214114272,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('40. 마지뜨락', '마지뜨락')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '40. 마지뜨락'
   );

MERGE INTO LOCATIONS L
USING (SELECT '40. 마지뜨락' LOCATION_NAME, 35.12222197234009 LATITUDE, 129.10011214114272 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '40. 마지뜨락')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('마지뜨락'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '40. 마지뜨락')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('마지뜨락'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '40. 마지뜨락')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('마지뜨락'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('마지뜨락');

-- 41. 분수대
UPDATE LOCATIONS
   SET LOCATION_NAME = '41. 분수대',
       BUILDING_NAME = '41. 분수대',
       DETAIL = '41. 분수대',
       LATITUDE = 35.12294034887136,
       LONGITUDE = 129.10129870579755,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('41. 분수대', '분수대')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '41. 분수대'
   );

MERGE INTO LOCATIONS L
USING (SELECT '41. 분수대' LOCATION_NAME, 35.12294034887136 LATITUDE, 129.10129870579755 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '41. 분수대')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('분수대'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '41. 분수대')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('분수대'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '41. 분수대')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('분수대'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('분수대');

-- 42. 학생휴게점(cafe)
UPDATE LOCATIONS
   SET LOCATION_NAME = '42. 학생휴게점(cafe)',
       BUILDING_NAME = '42. 학생휴게점(cafe)',
       DETAIL = '42. 학생휴게점(cafe)',
       LATITUDE = 35.122461452951576,
       LONGITUDE = 129.10267113385467,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('42. 학생휴게점(cafe)', '학생휴게점(cafe)')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '42. 학생휴게점(cafe)'
   );

MERGE INTO LOCATIONS L
USING (SELECT '42. 학생휴게점(cafe)' LOCATION_NAME, 35.122461452951576 LATITUDE, 129.10267113385467 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '42. 학생휴게점(cafe)')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생휴게점(cafe)'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '42. 학생휴게점(cafe)')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생휴게점(cafe)'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '42. 학생휴게점(cafe)')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('학생휴게점(cafe)'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('학생휴게점(cafe)');

-- 43. 동명생활관 (1호관)
UPDATE LOCATIONS
   SET LOCATION_NAME = '43. 동명생활관 (1호관)',
       BUILDING_NAME = '43. 동명생활관 (1호관)',
       DETAIL = '43. 동명생활관 (1호관)',
       LATITUDE = 35.117042587413465,
       LONGITUDE = 129.1063402809453,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('43. 동명생활관 (1호관)', '동명생활관 (1호관)', '동명생활관(1호관)')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '43. 동명생활관 (1호관)'
   );

MERGE INTO LOCATIONS L
USING (SELECT '43. 동명생활관 (1호관)' LOCATION_NAME, 35.117042587413465 LATITUDE, 129.1063402809453 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '43. 동명생활관 (1호관)')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명생활관 (1호관)', '동명생활관(1호관)'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '43. 동명생활관 (1호관)')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명생활관 (1호관)', '동명생활관(1호관)'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '43. 동명생활관 (1호관)')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명생활관 (1호관)', '동명생활관(1호관)'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('동명생활관 (1호관)', '동명생활관(1호관)');

-- 44. 동명뜰
UPDATE LOCATIONS
   SET LOCATION_NAME = '44. 동명뜰',
       BUILDING_NAME = '44. 동명뜰',
       DETAIL = '44. 동명뜰',
       LATITUDE = 35.12059237931578,
       LONGITUDE = 129.10418052811548,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('44. 동명뜰', '동명뜰')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '44. 동명뜰'
   );

MERGE INTO LOCATIONS L
USING (SELECT '44. 동명뜰' LOCATION_NAME, 35.12059237931578 LATITUDE, 129.10418052811548 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '44. 동명뜰')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명뜰'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '44. 동명뜰')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명뜰'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '44. 동명뜰')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('동명뜰'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('동명뜰');

-- 45. 체육시설관리동
UPDATE LOCATIONS
   SET LOCATION_NAME = '45. 체육시설관리동',
       BUILDING_NAME = '45. 체육시설관리동',
       DETAIL = '45. 체육시설관리동',
       LATITUDE = 35.121337297589676,
       LONGITUDE = 129.100980577376,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('45. 체육시설관리동', '체육시설관리동')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '45. 체육시설관리동'
   );

MERGE INTO LOCATIONS L
USING (SELECT '45. 체육시설관리동' LOCATION_NAME, 35.121337297589676 LATITUDE, 129.100980577376 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '45. 체육시설관리동')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('체육시설관리동'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '45. 체육시설관리동')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('체육시설관리동'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '45. 체육시설관리동')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('체육시설관리동'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('체육시설관리동');

-- 46. 그린스타트업타운
UPDATE LOCATIONS
   SET LOCATION_NAME = '46. 그린스타트업타운',
       BUILDING_NAME = '46. 그린스타트업타운',
       DETAIL = '46. 그린스타트업타운',
       LATITUDE = 35.11954635785008,
       LONGITUDE = 129.10084409007936,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('46. 그린스타트업타운', '그린스타트업타운')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '46. 그린스타트업타운'
   );

MERGE INTO LOCATIONS L
USING (SELECT '46. 그린스타트업타운' LOCATION_NAME, 35.11954635785008 LATITUDE, 129.10084409007936 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '46. 그린스타트업타운')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('그린스타트업타운'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '46. 그린스타트업타운')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('그린스타트업타운'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '46. 그린스타트업타운')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('그린스타트업타운'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('그린스타트업타운');

-- 47. 대학동물병원
UPDATE LOCATIONS
   SET LOCATION_NAME = '47. 대학동물병원',
       BUILDING_NAME = '47. 대학동물병원',
       DETAIL = '47. 대학동물병원',
       LATITUDE = 35.11895422185826,
       LONGITUDE = 129.1019914585962,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('47. 대학동물병원', '대학동물병원', '대학동명병원')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '47. 대학동물병원'
   );

MERGE INTO LOCATIONS L
USING (SELECT '47. 대학동물병원' LOCATION_NAME, 35.11895422185826 LATITUDE, 129.1019914585962 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '47. 대학동물병원')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학동물병원', '대학동명병원'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '47. 대학동물병원')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학동물병원', '대학동명병원'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '47. 대학동물병원')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('대학동물병원', '대학동명병원'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('대학동물병원', '대학동명병원');

-- 48. 창업거점지구
UPDATE LOCATIONS
   SET LOCATION_NAME = '48. 창업거점지구',
       BUILDING_NAME = '48. 창업거점지구',
       DETAIL = '48. 창업거점지구',
       LATITUDE = 35.119230010164635,
       LONGITUDE = 129.10063854556128,
       USE_YN = 'Y'
 WHERE LOCATION_ID = (
       SELECT MIN(LOCATION_ID)
         FROM LOCATIONS
        WHERE LOCATION_NAME IN ('48. 창업거점지구', '창업거점지구')
   )
   AND NOT EXISTS (
       SELECT 1
         FROM LOCATIONS
        WHERE LOCATION_NAME = '48. 창업거점지구'
   );

MERGE INTO LOCATIONS L
USING (SELECT '48. 창업거점지구' LOCATION_NAME, 35.119230010164635 LATITUDE, 129.10063854556128 LONGITUDE FROM DUAL) S
ON (L.LOCATION_NAME = S.LOCATION_NAME)
WHEN MATCHED THEN UPDATE SET L.LATITUDE = S.LATITUDE, L.LONGITUDE = S.LONGITUDE, L.USE_YN = 'Y'
WHEN NOT MATCHED THEN INSERT (LOCATION_ID, LOCATION_NAME, BUILDING_NAME, FLOOR, DETAIL, LATITUDE, LONGITUDE, USE_YN, CREATED_AT)
VALUES ((SELECT NVL(MAX(LOCATION_ID), 0) + 1 FROM LOCATIONS), S.LOCATION_NAME, S.LOCATION_NAME, NULL, S.LOCATION_NAME, S.LATITUDE, S.LONGITUDE, 'Y', SYSDATE);

UPDATE LOST_ITEMS
   SET LOST_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '48. 창업거점지구')
 WHERE LOST_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('창업거점지구'));

UPDATE FOUND_ITEMS
   SET FOUND_LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '48. 창업거점지구')
 WHERE FOUND_LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('창업거점지구'));

UPDATE STORAGE_PLACES
   SET LOCATION_ID = (SELECT MIN(LOCATION_ID) FROM LOCATIONS WHERE LOCATION_NAME = '48. 창업거점지구')
 WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM LOCATIONS WHERE LOCATION_NAME IN ('창업거점지구'));

UPDATE LOCATIONS
   SET USE_YN = 'N'
 WHERE LOCATION_NAME IN ('창업거점지구');

COMMIT;